jobs:
  include:
    - name: "Python 3.7 on Linux (ARM64)"
      arch: arm64
      env: RELEASE_FILENAME=bilidrive-$TRAVIS_TAG-linux-arm64.tar.gz
      language: python
      python: 3.7
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install pyinstaller
script:
  - pyinstaller -F -n BiliDrive drive.py
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: dist/BiliDrive
  overwrite: true
  skip_cleanup: true
  tag_name: v0.1.0
